### ISSUE TITLE
New QB Item List, Images Still the same

### ISSUE THREAD

**Issue by NataliaLFC** [Marshxan/qb-inventoryfood#10]
marshy_aero 				 	 = {name = 'marshy_aero', 			  	  	label = 'Aero', 					weight = 200, 		type = 'item', 		image = 'marshy-aero.png', 				unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_beanz 				 	 = {name = 'marshy_beanz', 			  	  	label = 'Beans', 					weight = 200, 		type = 'item', 		image = 'marshy-beanz.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_bourbon 				 	 = {name = 'marshy_bourbon', 			  	label = 'Bourbon', 					weight = 200, 		type = 'item', 		image = 'marshy-bourbon.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_bubbaloo 				 = {name = 'marshy_bubbaloo', 			  	label = 'Bubbaloo', 				weight = 200, 		type = 'item', 		image = 'marshy-bubbaloo.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_bueno 				 	 = {name = 'marshy_bueno', 			  	  	label = 'Bueno', 					weight = 200, 		type = 'item', 		image = 'marshy-bueno.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_chrunchie 				 = {name = 'marshy_chrunchie', 			  	label = 'Crunchie', 				weight = 200, 		type = 'item', 		image = 'marshy-chrunchie.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_corner_bcf 				 = {name = 'marshy_corner_bcf', 			label = 'Corner Banana', 			weight = 200, 		type = 'item', 		image = 'marshy-corner-bcf.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_corner_s 				 = {name = 'marshy_corner_s', 			  	label = 'Corner Strawberry', 		weight = 200, 		type = 'item', 		image = 'marshy-corner-s.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_corner_vcb 				 = {name = 'marshy_corner_vcb', 			label = 'Corner Chocolate', 		weight = 200, 		type = 'item', 		image = 'marshy-corner-vcb.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_creame_egg 				 = {name = 'marshy_creame_egg', 			label = 'Creame Egg', 				weight = 200, 		type = 'item', 		image = 'marshy-creame-egg.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_crumpets 				 = {name = 'marshy_crumpets', 			  	label = 'Crumpets', 				weight = 200, 		type = 'item', 		image = 'marshy-crumpets.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_custard_cream 			 = {name = 'marshy_custard_cream', 			label = 'Custard Creams', 			weight = 200, 		type = 'item', 		image = 'marshy-custard-cream.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_dairymilk 				 = {name = 'marshy_dairymilk', 			  	label = 'Dairy Milk', 				weight = 200, 		type = 'item', 		image = 'marshy-dairymilk.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_dibdabs 				 	 = {name = 'marshy_dibdabs', 			  	label = 'Dibdabs', 					weight = 200, 		type = 'item', 		image = 'marshy-dibdabs.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_digestive 				 = {name = 'marshy_digestive', 			  	label = 'Digestive', 				weight = 200, 		type = 'item', 		image = 'marshy-digestive.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_dorito_classic 			 = {name = 'marshy_dorito_classic', 		label = 'Doritos Classic', 			weight = 200, 		type = 'item', 		image = 'marshy-dorito-classic.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_dorito_coolranch 		 = {name = 'marshy_dorito_coolranch',		label = 'Doritos Coolranch', 		weight = 200, 		type = 'item', 		image = 'marshy-dorito-coolranch.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_dorito_flaming 			 = {name = 'marshy_dorito_flaming', 		label = 'Doritos Flaming', 			weight = 200, 		type = 'item', 		image = 'marshy-dorito-flaming.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_dorito_heatwave 			 = {name = 'marshy_dorito_heatwave', 		label = 'Doritos Chilly', 			weight = 200, 		type = 'item', 		image = 'marshy-dorito-heatwave.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
   	marshy_dunkers 				 	 = {name = 'marshy_dunkers', 			  	label = 'Dunkers', 					weight = 200, 		type = 'item', 		image = 'marshy-dunkers.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_flake 				 	 = {name = 'marshy_flake', 			  	  	label = 'Flake', 					weight = 200, 		type = 'item', 		image = 'marshy-flake.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_frazzles 				 = {name = 'marshy_frazzles', 			  	label = 'Frazzles', 				weight = 200, 		type = 'item', 		image = 'marshy-frazzles.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_greggs_d 				 = {name = 'marshy_greggs_sb', 			  	label = 'Steak Bake', 				weight = 200, 		type = 'item', 		image = 'marshy-greggs-sb.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_greggs_sr 				 = {name = 'marshy_greggs_sr', 			  	label = 'Sausage Roll', 			weight = 200, 		type = 'item', 		image = 'marshy-greggs-sr.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_hobnobs 				 	 = {name = 'marshy_hobnobs', 			  	label = 'Hobnobs', 					weight = 200, 		type = 'item', 		image = 'marshy-hobnobs.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_hula_hoops 				 = {name = 'marshy_hula_hoops', 			label = 'Hula Hoops', 				weight = 200, 		type = 'item', 		image = 'marshy-hula-hoops.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_jammy_dodger 			 = {name = 'marshy_jammy_dodger', 			label = 'Jammy Dodger', 			weight = 200, 		type = 'item', 		image = 'marshy-jammy-dodger.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_kipling 				 	 = {name = 'marshy_kipling', 			  	label = 'Kipling', 					weight = 200, 		type = 'item', 		image = 'marshy-kipling.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_kitkat 				 	 = {name = 'marshy_kp_peanuts', 			label = 'KP Peanuts', 				weight = 200, 		type = 'item', 		image = 'marshy-kp-peanuts.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_malteasers 				 = {name = 'marshy_malteasers', 			label = 'Malteasers', 				weight = 200, 		type = 'item', 		image = 'marshy-malteasers.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_maoam_stripes 			 = {name = 'marshy_maoam_stripes', 			label = 'Maoam Stripes', 			weight = 200, 		type = 'item', 		image = 'marshy-maoam-stripes.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_marylands 				 = {name = 'marshy_marylands', 			  	label = 'MaryLands', 				weight = 200, 		type = 'item', 		image = 'marshy-marylands.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_mccoys_fgs 				 = {name = 'marshy_mccoys_fgs', 			label = 'Mccoys Flame Grilled', 	weight = 200, 		type = 'item', 		image = 'marshy-mccoys-fgs.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_mccoys_salted 			 = {name = 'marshy_mccoys_salted', 			label = 'Mccoys Salted', 			weight = 200, 		type = 'item', 		image = 'marshy-mccoys-salted.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_mccoys_sav 				 = {name = 'marshy_mccoys_sav', 			label = 'Mccoys Salt & Vinegar', 	weight = 200, 		type = 'item', 		image = 'marshy-mccoys-sav.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_mccoys_tsc 				 = {name = 'marshy_mccoys_tsc', 			label = 'Mccoys Sweet Chicken', 	weight = 200, 		type = 'item', 		image = 'marshy-mccoys-tsc.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_milkeybar 				 = {name = 'marshy_milkeybar', 			  	label = 'Milkybar', 				weight = 200, 		type = 'item', 		image = 'marshy-milkeybar.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_milkeyway 				 = {name = 'marshy_milkeyway', 			  	label = 'Milkyway', 				weight = 200, 		type = 'item', 		image = 'marshy-milkeyway.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_millions 				 = {name = 'marshy_millions', 			  	label = 'Millions', 				weight = 200, 		type = 'item', 		image = 'marshy-millions.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_mini_rolls 				 = {name = 'marshy_mini_rolls', 			label = 'Mini Rolls', 				weight = 200, 		type = 'item', 		image = 'marshy-mini-rolls.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_monstor_munch 			 = {name = 'marshy_monstor_munch', 			label = 'Monstor Munch', 			weight = 200, 		type = 'item', 		image = 'marshy-monstor-munch.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_niknaks 				 	 = {name = 'marshy_niknaks', 			  	label = 'Niknaks', 					weight = 200, 		type = 'item', 		image = 'marshy-niknaks.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_penguin 				 	 = {name = 'marshy_penguin', 			  	label = 'Penguin', 					weight = 200, 		type = 'item', 		image = 'marshy-penguin.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_pom_bear 				 = {name = 'marshy_pom_bear', 			  	label = 'Pom Bear', 				weight = 200, 		type = 'item', 		image = 'marshy-pom-bear.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_pork_pie 				 = {name = 'marshy_pork_pie', 			  	label = 'Pork Pie', 				weight = 200, 		type = 'item', 		image = 'marshy-pork-pie.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_pot_noodle 				 = {name = 'marshy_pot_noodle', 			label = 'Pot Noodle', 				weight = 200, 		type = 'item', 		image = 'marshy-pot-noodle.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_pudding 				 	 = {name = 'marshy_pudding', 			  	label = 'Quaverspuddings', 			weight = 200, 		type = 'item', 		image = 'marshy-pudding.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_quavers 				 	 = {name = 'marshy_quavers', 			  	label = 'Quavers', 					weight = 200, 		type = 'item', 		image = 'marshy-quavers.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_sensations 				 = {name = 'marshy_sensations', 			label = 'Sensations', 				weight = 200, 		type = 'item', 		image = 'marshy-sensations.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_skips 				 	 = {name = 'marshy_skips', 			  	  	label = 'Skips', 					weight = 200, 		type = 'item', 		image = 'marshy-skips.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_skittles 				 = {name = 'marshy_skittles', 			  	label = 'Skittles', 				weight = 200, 		type = 'item', 		image = 'marshy-skittles.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_space_raiders 			 = {name = 'marshy_space_raiders', 			label = 'Space Raiders', 			weight = 200, 		type = 'item', 		image = 'marshy-space_raiders.png', 	unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_squashies 				 = {name = 'marshy_squashies', 			  	label = 'Squashies', 				weight = 200, 		type = 'item', 		image = 'marshy-squashies.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_starbursts 				 = {name = 'marshy_starbursts', 			label = 'Star Bursts', 				weight = 200, 		type = 'item', 		image = 'marshy-starbursts.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_tangfastics 				 = {name = 'marshy_tangfastics', 			label = 'Tangfastics', 				weight = 200, 		type = 'item', 		image = 'marshy-tangfastics.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_teacake 				 	 = {name = 'marshy_teacake', 			  	label = 'Tangfastics', 				weight = 200, 		type = 'item', 		image = 'marshy-teacake.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_timeout 				 	 = {name = 'marshy_timeout', 			  	label = 'Timeout', 					weight = 200, 		type = 'item', 		image = 'marshy-timeout.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_twirl 				 	 = {name = 'marshy_twirl', 			  	    label = 'Twirl', 					weight = 200, 		type = 'item', 		image = 'marshy-twirl.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_wagonwheel 				 = {name = 'marshy_wagonwheel', 			label = 'Wagon Wheel', 				weight = 200, 		type = 'item', 		image = 'marshy-wagonwheel.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_wispa 				 	 = {name = 'marshy_wispa', 			  	  	label = 'Wispa', 					weight = 200, 		type = 'item', 		image = 'marshy-wispa.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
    marshy_walkers_cao 				 = {name = 'marshy_walkers_cao', 			label = 'Walkers Cheese & Onion', 	weight = 200, 		type = 'item', 		image = 'marshy-walkers-cao.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_walkers_rc 				 = {name = 'marshy_walkers_rc', 			label = 'Walkers Roasted Chicken', 	weight = 200, 		type = 'item', 		image = 'marshy-walkers-rc.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_walkers_rs 				 = {name = 'marshy_walkers_rs', 			label = 'Walkers Ready Salted', 	weight = 200, 		type = 'item', 		image = 'marshy-walkers-rs.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_walkers_sav 				 = {name = 'marshy_walkers_sav', 			label = 'Walkers Salt & Vinegar', 	weight = 200, 		type = 'item', 		image = 'marshy-walkers-sav.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_marshmallow 				 = {name = 'marshy_marshmallow', 			label = 'Marshmallows', 			weight = 200, 		type = 'item', 		image = 'marshy-marshmallow.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_maxibon 				 	 = {name = 'marshy_maxibon', 				label = 'Maxibon', 					weight = 200, 		type = 'item', 		image = 'marshy-maxibon.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_pringles_o 				 = {name = 'marshy_pringles_o', 			label = 'Pringles Original', 		weight = 200, 		type = 'item', 		image = 'marshy-pringles-o.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_pringles_sc 				 = {name = 'marshy_pringles_sc', 			label = 'Pringles Sour Cream', 		weight = 200, 		type = 'item', 		image = 'marshy-pringles-sc.png', 		unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},
	marshy_starmix 				 	 = {name = 'marshy_starmix', 				label = 'Haribo Starmix', 			weight = 200, 		type = 'item', 		image = 'marshy-starmix.png', 			unique = false, 	useable = true, 	shouldClose = true,	   combinable = nil,   description = 'Yummy'},

**Comment by Marshxan** [comment]
very nice thank you
